#!/bin/sh

sudo -u postgres psql -c "CREATE ROLE dhis2 WITH ENCRYPTED PASSWORD 'dhis2';"
sudo -u postgres psql -c "ALTER USER dhis2 LOGIN;"
sudo -u postgres createdb -O postgres dhis2

add-apt-repository ppa:webupd8team/java
apt-get update
apt-get install python-software-properties
apt-get -y install tomcat7-user
tomcat7-instance-create dhis2-server
unzip -o dhis.war -d dhis2-server/webapps/dhis2
