#!/bin/sh
export DHIS2_HOME='/vagrant/dhis2-home'
echo "Using DHIS2_HOME: $DHIS2_HOME"

export JAVA_OPTS='-Xmx1000m -XX:MaxPermSize=200m'
echo "Using JAVA_OPTS: $JAVA_OPTS"

/vagrant/dhis2-server/bin/startup.sh && tail -f /vagrant/dhis2-server/logs/catalina.out
